global:
  imagePullSecret: {}
  image: {}
  partOf: susaas
  component: broker
  domain: 
  gateway: 
  api:
    fullName:
    deploymentHost: 

port: 5000

serviceAccount:
  enabled: false # If true, own serviceAccount (<<ReleaseName>>-broker) used by pod, otherwise "default" serviceAccount
  automountToken: false # If true, token of the assigned serviceAccount (default or fullname) auto-mounted

image: {}
imagePullSecret: {}
additionalVolumes: []

config: 
  serviceId: # Leave empty to generate new ID on Helm installation
  displayName:  # Allows tpl usage
  plans: [] # Provide service plans

expose:
  enabled: true

ha:
  enabled: true
  pdb:
    minAvailable: 1

hpa:
  enabled: true
  minReplicaCount: 1 # To use High-Availability set minReplicaCount to at least 2
  maxReplicaCount: 3
  cpuTargetAverageUtilization: 80
  cpuTargetAverageValue:

health_check:
  liveness:
    path: /health
  readiness:
    path: /health

securityContext:
  user:
  group: 

startupTimeout: 30
resources:
  limits:
      ephemeral-storage: 
      memory: 
      cpu: 
  requests:
    ephemeral-storage: 
    cpu: 
    memory: 

envSecretNames: []

envSecretNamesTpl: 
  - "{{ .Release.Name }}-broker"

env:
  - name: SBF_ENABLE_AUDITLOG
    value: 'false'