{{- if and .Values.expose.enabled .Values.apim }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s-%s" ( include "susaas-api.fullname" . ) ( uuidv4 | trunc 5) }}
  labels: {{- include "susaas-api.labels" . | nindent 4 }}
spec:
  gateways: 
    - {{ .Values.global.gateway | default "kyma-system/kyma-gateway"  }}
  hosts: 
    - {{ printf "%s.%s" ( include "susaas-api.exposeHost" . ) $.Values.global.domain }}
  http:
  - match:
    - headers:
        x-jwt-assertion: {}
    route:
    - destination:
        host: {{ printf "%s.%s.svc.cluster.local" ( include "susaas-api.fullname" . ) .Release.Namespace  }} 
        port:
          number: {{ .Values.port }}
  - match:
    - withoutHeaders:
        x-jwt-assertion: {}
    rewrite:
      uri: {{ printf "/%s/" .Values.apim.path }}
      authority: {{ .Values.apim.host }}
    route:
    - destination:
        host: {{ .Values.apim.host }}
        port:
          number: {{ default 443 .Values.apim.port }}
{{- end }}