apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "susaas-broker.fullname" . }}-config
  labels: {{- include "susaas-broker.labels" . | nindent 4 }}
data:
  serviceConfigs: | 
    {   
        "{{ printf "%s-api-%s-%s" .Release.Name .Release.Namespace .Values.global.shootName }}": {
            "extend_credentials": {
                "shared": {
                    "apiUrl": "{{ printf "https://%s.%s" ( default .Values.global.api.deploymentHost ( printf "%s-%s-%s" .Release.Name "api" .Release.Namespace ) ) .Values.global.domain  }}"
                }
            },
            "extend_xssecurity": {
                "per_plan": {
                    {{ range $i, $plans := .Values.config.plans }}
                    {{- if $i  -}},{{- end -}}
                    "{{ $plans.name }}": {
                        "authorities": [
                            "$XSMASTERAPPNAME.plan_{{ $plans.name }}"
                        ]
                    }
                    {{- end }}
                }
            },
            "extend_catalog": {
                "metadata": {
                    "displayName": "{{ .Values.config.displayName }}"
                }
            }
        }
    }