{{- $srvHostFull := include "cap.deploymentHostFull" (merge (dict "name" "srv" "deployment" .Values.srv) . ) }}
{{- $defaultAppUrls := dict
  "getDependencies" (print "https://" $srvHostFull "/-/cds/saas-provisioning/dependencies")
  "onSubscription" (print "https://" $srvHostFull "/-/cds/saas-provisioning/tenant/{tenantId}")
  "onSubscriptionAsync" false
  "onUnSubscriptionAsync" false
  "callbackTimeoutMillis" 300000
}}
{{- $defaultParameters := dict
    "xsappname" (printf "%s" .Values.xsuaa.parameters.xsappname)
    "appName" (printf "%s-%s" .Values.xsuaa.parameters.xsappname .Values.global.shootName)
    "displayName" .Chart.Description
    "description" (printf "%s (%s-%s)" .Chart.Description .Values.xsuaa.parameters.xsappname .Values.global.shootName)
    "category" "CAP Application"
    "appUrls" $defaultAppUrls
}}
{{- include "cap.service-instance" (mergeOverwrite (dict "defaultParameters" $defaultParameters ) .) }}