{{- if or (not (hasKey .Values.serviceAccount "enabled")) .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "susaas-api.fullname" . }}
  labels: {{- include "susaas-api.labels" . | nindent 4 }}
{{- end }}